import { Header } from '@/components/header'
import type { Metadata } from 'next'
import { Comfortaa, Inter } from 'next/font/google'
import './globals.css'

const comfortaa = Comfortaa({
  subsets: ['latin'],
  display: 'swap',
  weight: '500',
  variable: '--font-comfortaa',
})

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Tunescape',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${comfortaa.variable} ${inter.variable} font-sans w-full`}
      >
        <Header />
        <main className="max-w-5xl p-4 mx-auto">{children}</main>
      </body>
    </html>
  )
}
